apiVersion: v1
kind: Pod
metadata:
  name: postgres-2
  labels:
    app: postgres-2
spec:
  containers:
    - name: postgres
      image: postgres:9.6.17-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "pwd"